name: C CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Compilar o código C
      run: gcc main.c -o soma

    - name: Executar o código compilado
      run: ./soma
